name: Deploy

on:
  workflow_run:
    workflows: ["Code Integration"]
    types:
      - completed
      
jobs:
  deploy:

    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
      
    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t fsadocker1/java-app
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push fsadocker1/java-app:latest
